Repository AY2324S2-CS2113-T12-3/tp, pull requests merged in 2024-03, with the labels that each got.

#70 Implement Splitter
  docs/UserGuide.md
  src/main/java/seedu/budgetbuddy/BudgetBuddy.java
  src/main/java/seedu/budgetbuddy/Parser.java
  src/main/java/seedu/budgetbuddy/SplitExpense.java
  src/main/java/seedu/budgetbuddy/SplitExpenseList.java
  src/main/java/seedu/budgetbuddy/Ui.java
  src/main/java/seedu/budgetbuddy/command/EditExpenseCommand.java
  src/main/java/seedu/budgetbuddy/command/ListSplitExpenseCommand.java
  src/main/java/seedu/budgetbuddy/command/SplitExpenseCommand.java
  src/test/java/seedu/budgetbuddy/ParserTest.java
  src/test/java/seedu/budgetbuddy/SplitExpenses.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Low

#62 Implement Currency Converter
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CurrencyConverter_SequenceDiagram.png
  docs/diagrams/ExpenseList_SequenceDiagram.png
  docs/diagrams/SavingList_SequenceDiagram.png
  src/main/java/seedu/budgetbuddy/CurrencyConverter.java
  src/main/java/seedu/budgetbuddy/ExpenseList.java
  src/main/java/seedu/budgetbuddy/Parser.java
  src/main/java/seedu/budgetbuddy/SavingList.java
  src/main/java/seedu/budgetbuddy/Transaction.java
  src/main/java/seedu/budgetbuddy/command/ChangeCurrencyCommand.java
  src/test/java/seedu/budgetbuddy/CurrencyConverterTest.java
  src/test/java/seedu/budgetbuddy/ParserTest.java
Labels: priority.Medium, type.Story

#79 Add AddExpense into DG
  docs/DeveloperGuide.md
  docs/diagram/sequenceDiagram_AddExpense.png
Labels: priority.Low

#89 Refactor my features in Parser into separate CommandCreator classes
  src/main/java/seedu/budgetbuddy/ExpenseList.java
  src/main/java/seedu/budgetbuddy/Parser.java
  src/main/java/seedu/budgetbuddy/SavingList.java
  src/main/java/seedu/budgetbuddy/commandcreator/ChangeCurrencyCommandCreator.java
  src/main/java/seedu/budgetbuddy/commandcreator/ListCommandCreator.java
  src/main/java/seedu/budgetbuddy/data/ExpenseFile.txt
  src/main/java/seedu/budgetbuddy/data/SavingsFile.txt
  src/test/java/seedu/budgetbuddy/ChangeCurrencyCommandCreatorTest.java
  src/test/java/seedu/budgetbuddy/ListCommandCreatorTest.java
  src/test/java/seedu/budgetbuddy/ParserTest.java
Labels: priority.Medium, type.Task

#104 Add UI for Currency Converter
  src/main/java/seedu/budgetbuddy/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Task
