Repository AY2324S2-CS2113-T12-3/tp, pull requests merged in 2024-04, with the labels that each got.

#191 Bug Fixes for my features
  docs/UserGuide.md
  docs/diagrams/CurrencyConverter_SequenceDiagram.png
  docs/diagrams/ExpenseList_SequenceDiagram.png
  docs/diagrams/SavingList_SequenceDiagram.png
  docs/userguideimages/CurrencyConverter_ChangeUSD.PNG
  docs/userguideimages/CurrencyConverter_SameCurrency.PNG
  docs/userguideimages/ListExpenses_EmptyExpense.PNG
  docs/userguideimages/ListExpenses_ExpenseRecorded.PNG
  docs/userguideimages/ListExpenses_FilteredCategory.PNG
  docs/userguideimages/ListSavings_EmptyExpense.PNG
  docs/userguideimages/ListSavings_EmptySaving.PNG
  docs/userguideimages/ListSavings_ExpenseRecorded.PNG
  docs/userguideimages/ListSavings_FilterCategory.PNG
  src/main/java/seedu/budgetbuddy/BudgetBuddy.java
  src/main/java/seedu/budgetbuddy/Parser.java
  src/main/java/seedu/budgetbuddy/command/ListExpenseCommand.java
  src/main/java/seedu/budgetbuddy/command/ListSavingsCommand.java
  src/main/java/seedu/budgetbuddy/commandcreator/ChangeCurrencyCommandCreator.java
  src/main/java/seedu/budgetbuddy/commandcreator/ListCommandCreator.java
  src/main/java/seedu/budgetbuddy/commons/CurrencyConverter.java
  src/main/java/seedu/budgetbuddy/commons/ExpenseList.java
  src/main/java/seedu/budgetbuddy/commons/SavingList.java
Labels: severity.Medium, type.Bug

#193 Add PPP
  docs/DeveloperGuide.md
  docs/team/sweijie24.md
Labels: priority.High, type.Task

#207 Bug fixing & PPP & UG & DG
  data/DefaultCurrency.txt
  data/ExpenseFile.txt
  data/SavingsFile.txt
  data/SplitExpensesFile.txt
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SequenceDiagram_addSavings.png
  docs/diagrams/sequenceDiagram_AddExpense.jpg
  docs/diagrams/sequenceDiagram_AddExpense.png
  docs/diagrams/sequenceDiagram_AddSaving.jpg
  docs/diagrams/sequenceDiagram_SplitExpense.jpg
  docs/team/yyangdaa.md
  src/main/java/seedu/budgetbuddy/BudgetBuddy.java
  src/main/java/seedu/budgetbuddy/Parser.java
  src/main/java/seedu/budgetbuddy/Storage.java
  src/main/java/seedu/budgetbuddy/command/AddExpenseCommand.java
  src/main/java/seedu/budgetbuddy/command/AddSavingCommand.java
  src/main/java/seedu/budgetbuddy/command/ChangeCurrencyCommand.java
  src/main/java/seedu/budgetbuddy/commandcreator/AddSavingCommandCreator.java
  src/main/java/seedu/budgetbuddy/commandcreator/ChangeCurrencyCommandCreator.java
  src/main/java/seedu/budgetbuddy/commandcreator/SplitExpenseCommandCreator.java
  src/main/java/seedu/budgetbuddy/commons/CurrencyConverter.java
  src/main/java/seedu/budgetbuddy/commons/ExpenseList.java
  src/main/java/seedu/budgetbuddy/commons/SavingList.java
  src/main/java/seedu/budgetbuddy/commons/SplitExpense.java
  src/main/java/seedu/budgetbuddy/commons/SplitExpenseList.java
  src/test/java/seedu/budgetbuddy/ChangeCurrencyCommandCreatorTest.java
  src/test/java/seedu/budgetbuddy/ExpenseListTest.java
  src/test/java/seedu/budgetbuddy/SavingListTest.java
  src/test/java/seedu/budgetbuddy/SplitExpenseListTest.java
Labels: priority.High

#213 Add DG/UG Enhancements
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CurrencyConverter_RecurringExpenses_SequenceDiagram.png
  docs/diagrams/budgetCurrencyConverter.png
  docs/diagrams/convertExpenseCurrency_SequenceDiagram.png
  docs/diagrams/convertSavingCurrency_SequenceDiagram.png
  docs/team/sweijie24.md
Labels: priority.High, type.Task

#228 Refine DG & UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CurrencyConverter_SequenceDiagram.png
  docs/diagrams/EditExpenseDiagram.drawio.png
  docs/diagrams/sequenceDiagram_CurrencyConverter_SplitExpense.png
  src/main/java/seedu/budgetbuddy/Storage.java
  src/main/java/seedu/budgetbuddy/command/ChangeCurrencyCommand.java
  src/main/java/seedu/budgetbuddy/commandcreator/ChangeCurrencyCommandCreator.java
  src/main/java/seedu/budgetbuddy/commandcreator/ListCommandCreator.java
  src/main/java/seedu/budgetbuddy/commons/CurrencyConverter.java
  src/main/java/seedu/budgetbuddy/commons/DefaultCurrency.java
  src/main/java/seedu/budgetbuddy/commons/Expense.java
  src/main/java/seedu/budgetbuddy/commons/ExpenseList.java
  src/main/java/seedu/budgetbuddy/commons/Saving.java
  src/main/java/seedu/budgetbuddy/commons/SavingList.java
  src/test/java/seedu/budgetbuddy/ChangeCurrencyCommandCreatorTest.java
  src/test/java/seedu/budgetbuddy/CurrencyConverterTest.java
  src/test/java/seedu/budgetbuddy/ExpenseListTest.java
  src/test/java/seedu/budgetbuddy/ListCommandCreatorTest.java
  src/test/java/seedu/budgetbuddy/SavingListTest.java
Labels: priority.High, type.Task
